test_lab1:
  image: ipadsse302/tigerlabs_score_env
  tags:
    - r743
  stage: test
  script:
    - rm -rf scripts testdata
    - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
    - make gradelab1

test_lab2:
  image: ipadsse302/tigerlabs_score_env
  tags:
    - r743
  stage: test
  script:
    - rm -rf scripts testdata
    - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
    - make gradelab2

test_lab3:
  image: ipadsse302/tigerlabs_score_env
  tags:
    - r743
  stage: test
  script:
    - rm -rf scripts testdata
    - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
    - make gradelab3

test_lab4:
  image: ipadsse302/tigerlabs_score_env
  tags:
    - r743
  stage: test
  script:
    - rm -rf scripts testdata
    - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
    - make gradelab4

test_lab5_part1:
 image: ipadsse302/tigerlabs_score_env
 tags:
   - r743
 stage: test
 script:
   - rm -rf scripts testdata
   - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
   - make gradelab5-1

test_lab5:
 image: ipadsse302/tigerlabs_score_env
 tags:
   - r743
 stage: test
 script:
   - rm -rf scripts testdata
   - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
   - make gradelab5

test_lab6:
  image: ipadsse302/tigerlabs_score_env
  tags:
    - r743
  stage: test
  script:
    - rm -rf scripts testdata
    - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
    - make gradelab6 | tee output.log

test_lab7:
  image: ipadsse302/tigerlabs_score_env
  tags:
    - r743
  stage: test
  script:
    - rm -rf scripts testdata
    - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
    - make gradelab7 | tee output.log

